name: CI/CD Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  # Job de test pour PR
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Node.js (si applicable)
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies Front
        run: npm install
        working-directory: front

      - name: Run tests Front
        run: npm test
        working-directory: front

      - name: Install dependencies Back
        run: npm install
        working-directory: back

  # Job de build et de publication de l'image Docker lors du merge sur main
  build_and_publish:
    runs-on: ubuntu-latest
    needs: test # Ce job dépend du job test réussi
    if: github.ref == 'refs/heads/main' # Ce job s'exécute uniquement sur des push vers main
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Frontend Docker image with commit SHA
        run: |
          docker build -t loutron34/ibiccicd-front:${{ github.sha }} -f front/Dockerfile front/
          docker push loutron34/ibiccicd-front:${{ github.sha }}

      - name: Build and push Backend Docker image with commit SHA
        run: |
          docker build -t loutron34/ibiccicd-back:${{ github.sha }} -f back/Dockerfile back/
          docker push loutron34/ibiccicd-back:${{ github.sha }}

  # Job de release (tagging et push Docker)
  release:
    runs-on: ubuntu-latest
    needs: build_and_publish # Ce job dépend du job précédent
    if: github.event_name == 'release' # Ce job s'exécute uniquement lors d'une création de release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image with release tag
        run: |
          docker build -t loutron34/ibiccicd:${{ github.event.release.tag_name }} .
          docker push loutron34/ibiccicd:${{ github.event.release.tag_name }}
